/// Comprehensive list of worldwide countries with ISO codes and phone dial codes
/// Each entry has a unique 'id' (ISO 3166-1 alpha-2) to avoid duplicate values in dropdown
/// The 'code' is the actual phone country code, 'name' is the country name
/// Countries are sorted alphabetically by name
class WorldCountries {
  WorldCountries._();

  static List<Map<String, String>> get allCountries {
    final countries = List<Map<String, String>>.from(_unsortedCountries);
    countries.sort((a, b) => (a['name'] ?? '').compareTo(b['name'] ?? ''));
    return countries;
  }

  static const List<Map<String, String>> _unsortedCountries = [
    // North America
    {'id': 'US', 'code': '+1', 'name': 'United States'},
    {'id': 'CA', 'code': '+1', 'name': 'Canada'},
    {'id': 'MX', 'code': '+52', 'name': 'Mexico'},
    {'id': 'GT', 'code': '+502', 'name': 'Guatemala'},
    {'id': 'BZ', 'code': '+501', 'name': 'Belize'},
    {'id': 'SV', 'code': '+503', 'name': 'El Salvador'},
    {'id': 'HN', 'code': '+504', 'name': 'Honduras'},
    {'id': 'NI', 'code': '+505', 'name': 'Nicaragua'},
    {'id': 'CR', 'code': '+506', 'name': 'Costa Rica'},
    {'id': 'PA', 'code': '+507', 'name': 'Panama'},
    {'id': 'CU', 'code': '+53', 'name': 'Cuba'},
    {'id': 'JM', 'code': '+1', 'name': 'Jamaica'},
    {'id': 'HT', 'code': '+509', 'name': 'Haiti'},
    {'id': 'DO', 'code': '+1', 'name': 'Dominican Republic'},
    {'id': 'TT', 'code': '+1', 'name': 'Trinidad and Tobago'},
    {'id': 'BB', 'code': '+1', 'name': 'Barbados'},
    {'id': 'BS', 'code': '+1', 'name': 'Bahamas'},
    {'id': 'AG', 'code': '+1', 'name': 'Antigua and Barbuda'},
    {'id': 'DM', 'code': '+1', 'name': 'Dominica'},
    {'id': 'GD', 'code': '+1', 'name': 'Grenada'},
    {'id': 'KN', 'code': '+1', 'name': 'Saint Kitts and Nevis'},
    {'id': 'LC', 'code': '+1', 'name': 'Saint Lucia'},
    {'id': 'VC', 'code': '+1', 'name': 'Saint Vincent and the Grenadines'},

    // South America
    {'id': 'BR', 'code': '+55', 'name': 'Brazil'},
    {'id': 'AR', 'code': '+54', 'name': 'Argentina'},
    {'id': 'CO', 'code': '+57', 'name': 'Colombia'},
    {'id': 'PE', 'code': '+51', 'name': 'Peru'},
    {'id': 'VE', 'code': '+58', 'name': 'Venezuela'},
    {'id': 'CL', 'code': '+56', 'name': 'Chile'},
    {'id': 'EC', 'code': '+593', 'name': 'Ecuador'},
    {'id': 'BO', 'code': '+591', 'name': 'Bolivia'},
    {'id': 'PY', 'code': '+595', 'name': 'Paraguay'},
    {'id': 'UY', 'code': '+598', 'name': 'Uruguay'},
    {'id': 'GY', 'code': '+592', 'name': 'Guyana'},
    {'id': 'SR', 'code': '+597', 'name': 'Suriname'},
    {'id': 'GF', 'code': '+594', 'name': 'French Guiana'},
    {'id': 'FK', 'code': '+500', 'name': 'Falkland Islands'},

    // Europe
    {'id': 'GB', 'code': '+44', 'name': 'United Kingdom'},
    {'id': 'IE', 'code': '+353', 'name': 'Ireland'},
    {'id': 'FR', 'code': '+33', 'name': 'France'},
    {'id': 'DE', 'code': '+49', 'name': 'Germany'},
    {'id': 'IT', 'code': '+39', 'name': 'Italy'},
    {'id': 'ES', 'code': '+34', 'name': 'Spain'},
    {'id': 'PT', 'code': '+351', 'name': 'Portugal'},
    {'id': 'NL', 'code': '+31', 'name': 'Netherlands'},
    {'id': 'BE', 'code': '+32', 'name': 'Belgium'},
    {'id': 'CH', 'code': '+41', 'name': 'Switzerland'},
    {'id': 'AT', 'code': '+43', 'name': 'Austria'},
    {'id': 'SE', 'code': '+46', 'name': 'Sweden'},
    {'id': 'NO', 'code': '+47', 'name': 'Norway'},
    {'id': 'DK', 'code': '+45', 'name': 'Denmark'},
    {'id': 'FI', 'code': '+358', 'name': 'Finland'},
    {'id': 'PL', 'code': '+48', 'name': 'Poland'},
    {'id': 'CZ', 'code': '+420', 'name': 'Czech Republic'},
    {'id': 'SK', 'code': '+421', 'name': 'Slovakia'},
    {'id': 'HU', 'code': '+36', 'name': 'Hungary'},
    {'id': 'RO', 'code': '+40', 'name': 'Romania'},
    {'id': 'BG', 'code': '+359', 'name': 'Bulgaria'},
    {'id': 'GR', 'code': '+30', 'name': 'Greece'},
    {'id': 'TR', 'code': '+90', 'name': 'Turkey'},
    {'id': 'RU', 'code': '+7', 'name': 'Russia'},
    {'id': 'UA', 'code': '+380', 'name': 'Ukraine'},
    {'id': 'BY', 'code': '+375', 'name': 'Belarus'},
    {'id': 'LT', 'code': '+370', 'name': 'Lithuania'},
    {'id': 'LV', 'code': '+371', 'name': 'Latvia'},
    {'id': 'EE', 'code': '+372', 'name': 'Estonia'},
    {'id': 'IS', 'code': '+354', 'name': 'Iceland'},
    {'id': 'LU', 'code': '+352', 'name': 'Luxembourg'},
    {'id': 'LI', 'code': '+423', 'name': 'Liechtenstein'},
    {'id': 'MC', 'code': '+377', 'name': 'Monaco'},
    {'id': 'AD', 'code': '+376', 'name': 'Andorra'},
    {'id': 'SM', 'code': '+378', 'name': 'San Marino'},
    {'id': 'VA', 'code': '+39', 'name': 'Vatican City'},
    {'id': 'MT', 'code': '+356', 'name': 'Malta'},
    {'id': 'CY', 'code': '+357', 'name': 'Cyprus'},
    {'id': 'HR', 'code': '+385', 'name': 'Croatia'},
    {'id': 'SI', 'code': '+386', 'name': 'Slovenia'},
    {'id': 'BA', 'code': '+387', 'name': 'Bosnia and Herzegovina'},
    {'id': 'RS', 'code': '+381', 'name': 'Serbia'},
    {'id': 'ME', 'code': '+382', 'name': 'Montenegro'},
    {'id': 'MK', 'code': '+389', 'name': 'North Macedonia'},
    {'id': 'AL', 'code': '+355', 'name': 'Albania'},
    {'id': 'XK', 'code': '+383', 'name': 'Kosovo'},

    // Asia
    {'id': 'CN', 'code': '+86', 'name': 'China'},
    {'id': 'IN', 'code': '+91', 'name': 'India'},
    {'id': 'JP', 'code': '+81', 'name': 'Japan'},
    {'id': 'KR', 'code': '+82', 'name': 'South Korea'},
    {'id': 'KP', 'code': '+850', 'name': 'North Korea'},
    {'id': 'TW', 'code': '+886', 'name': 'Taiwan'},
    {'id': 'HK', 'code': '+852', 'name': 'Hong Kong'},
    {'id': 'MO', 'code': '+853', 'name': 'Macau'},
    {'id': 'SG', 'code': '+65', 'name': 'Singapore'},
    {'id': 'MY', 'code': '+60', 'name': 'Malaysia'},
    {'id': 'TH', 'code': '+66', 'name': 'Thailand'},
    {'id': 'VN', 'code': '+84', 'name': 'Vietnam'},
    {'id': 'PH', 'code': '+63', 'name': 'Philippines'},
    {'id': 'ID', 'code': '+62', 'name': 'Indonesia'},
    {'id': 'MM', 'code': '+95', 'name': 'Myanmar'},
    {'id': 'KH', 'code': '+855', 'name': 'Cambodia'},
    {'id': 'LA', 'code': '+856', 'name': 'Laos'},
    {'id': 'BN', 'code': '+673', 'name': 'Brunei'},
    {'id': 'BD', 'code': '+880', 'name': 'Bangladesh'},
    {'id': 'PK', 'code': '+92', 'name': 'Pakistan'},
    {'id': 'AF', 'code': '+93', 'name': 'Afghanistan'},
    {'id': 'LK', 'code': '+94', 'name': 'Sri Lanka'},
    {'id': 'MV', 'code': '+960', 'name': 'Maldives'},
    {'id': 'NP', 'code': '+977', 'name': 'Nepal'},
    {'id': 'BT', 'code': '+975', 'name': 'Bhutan'},
    {'id': 'IR', 'code': '+98', 'name': 'Iran'},
    {'id': 'IQ', 'code': '+964', 'name': 'Iraq'},
    {'id': 'SA', 'code': '+966', 'name': 'Saudi Arabia'},
    {'id': 'AE', 'code': '+971', 'name': 'United Arab Emirates'},
    {'id': 'KW', 'code': '+965', 'name': 'Kuwait'},
    {'id': 'QA', 'code': '+974', 'name': 'Qatar'},
    {'id': 'BH', 'code': '+973', 'name': 'Bahrain'},
    {'id': 'OM', 'code': '+968', 'name': 'Oman'},
    {'id': 'YE', 'code': '+967', 'name': 'Yemen'},
    {'id': 'JO', 'code': '+962', 'name': 'Jordan'},
    {'id': 'LB', 'code': '+961', 'name': 'Lebanon'},
    {'id': 'SY', 'code': '+963', 'name': 'Syria'},
    {'id': 'IL', 'code': '+972', 'name': 'Israel'},
    {'id': 'PS', 'code': '+970', 'name': 'Palestine'},
    {'id': 'KZ', 'code': '+7', 'name': 'Kazakhstan'},
    {'id': 'UZ', 'code': '+998', 'name': 'Uzbekistan'},
    {'id': 'TM', 'code': '+993', 'name': 'Turkmenistan'},
    {'id': 'TJ', 'code': '+992', 'name': 'Tajikistan'},
    {'id': 'KG', 'code': '+996', 'name': 'Kyrgyzstan'},
    {'id': 'MN', 'code': '+976', 'name': 'Mongolia'},
    {'id': 'AM', 'code': '+374', 'name': 'Armenia'},
    {'id': 'AZ', 'code': '+994', 'name': 'Azerbaijan'},
    {'id': 'GE', 'code': '+995', 'name': 'Georgia'},

    // Africa
    {'id': 'ZA', 'code': '+27', 'name': 'South Africa'},
    {'id': 'EG', 'code': '+20', 'name': 'Egypt'},
    {'id': 'NG', 'code': '+234', 'name': 'Nigeria'},
    {'id': 'KE', 'code': '+254', 'name': 'Kenya'},
    {'id': 'ET', 'code': '+251', 'name': 'Ethiopia'},
    {'id': 'GH', 'code': '+233', 'name': 'Ghana'},
    {'id': 'TZ', 'code': '+255', 'name': 'Tanzania'},
    {'id': 'UG', 'code': '+256', 'name': 'Uganda'},
    {'id': 'RW', 'code': '+250', 'name': 'Rwanda'},
    {'id': 'ZM', 'code': '+260', 'name': 'Zambia'},
    {'id': 'ZW', 'code': '+263', 'name': 'Zimbabwe'},
    {'id': 'MW', 'code': '+265', 'name': 'Malawi'},
    {'id': 'MZ', 'code': '+258', 'name': 'Mozambique'},
    {'id': 'AO', 'code': '+244', 'name': 'Angola'},
    {'id': 'CM', 'code': '+237', 'name': 'Cameroon'},
    {'id': 'SN', 'code': '+221', 'name': 'Senegal'},
    {'id': 'CI', 'code': '+225', 'name': 'Ivory Coast'},
    {'id': 'ML', 'code': '+223', 'name': 'Mali'},
    {'id': 'BF', 'code': '+226', 'name': 'Burkina Faso'},
    {'id': 'NE', 'code': '+227', 'name': 'Niger'},
    {'id': 'TD', 'code': '+235', 'name': 'Chad'},
    {'id': 'SD', 'code': '+249', 'name': 'Sudan'},
    {'id': 'SS', 'code': '+211', 'name': 'South Sudan'},
    {'id': 'ER', 'code': '+291', 'name': 'Eritrea'},
    {'id': 'DJ', 'code': '+253', 'name': 'Djibouti'},
    {'id': 'SO', 'code': '+252', 'name': 'Somalia'},
    {'id': 'MA', 'code': '+212', 'name': 'Morocco'},
    {'id': 'DZ', 'code': '+213', 'name': 'Algeria'},
    {'id': 'TN', 'code': '+216', 'name': 'Tunisia'},
    {'id': 'LY', 'code': '+218', 'name': 'Libya'},
    {'id': 'LR', 'code': '+231', 'name': 'Liberia'},
    {'id': 'SL', 'code': '+232', 'name': 'Sierra Leone'},
    {'id': 'GN', 'code': '+224', 'name': 'Guinea'},
    {'id': 'GW', 'code': '+245', 'name': 'Guinea-Bissau'},
    {'id': 'GM', 'code': '+220', 'name': 'Gambia'},
    {'id': 'CV', 'code': '+238', 'name': 'Cape Verde'},
    {'id': 'ST', 'code': '+239', 'name': 'São Tomé and Príncipe'},
    {'id': 'GA', 'code': '+241', 'name': 'Gabon'},
    {'id': 'CG', 'code': '+242', 'name': 'Republic of the Congo'},
    {'id': 'CD', 'code': '+243', 'name': 'DR Congo'},
    {'id': 'CF', 'code': '+236', 'name': 'Central African Republic'},
    {'id': 'GQ', 'code': '+240', 'name': 'Equatorial Guinea'},
    {'id': 'BI', 'code': '+257', 'name': 'Burundi'},
    {'id': 'MU', 'code': '+230', 'name': 'Mauritius'},
    {'id': 'SC', 'code': '+248', 'name': 'Seychelles'},
    {'id': 'KM', 'code': '+269', 'name': 'Comoros'},
    {'id': 'MG', 'code': '+261', 'name': 'Madagascar'},
    {'id': 'NA', 'code': '+264', 'name': 'Namibia'},
    {'id': 'BW', 'code': '+267', 'name': 'Botswana'},
    {'id': 'LS', 'code': '+266', 'name': 'Lesotho'},
    {'id': 'SZ', 'code': '+268', 'name': 'Eswatini'},
    {'id': 'MR', 'code': '+222', 'name': 'Mauritania'},
    {'id': 'BJ', 'code': '+229', 'name': 'Benin'},
    {'id': 'TG', 'code': '+228', 'name': 'Togo'},

    // Oceania
    {'id': 'AU', 'code': '+61', 'name': 'Australia'},
    {'id': 'NZ', 'code': '+64', 'name': 'New Zealand'},
    {'id': 'PG', 'code': '+675', 'name': 'Papua New Guinea'},
    {'id': 'FJ', 'code': '+679', 'name': 'Fiji'},
    {'id': 'NC', 'code': '+687', 'name': 'New Caledonia'},
    {'id': 'PF', 'code': '+689', 'name': 'French Polynesia'},
    {'id': 'WS', 'code': '+685', 'name': 'Samoa'},
    {'id': 'TO', 'code': '+676', 'name': 'Tonga'},
    {'id': 'VU', 'code': '+678', 'name': 'Vanuatu'},
    {'id': 'SB', 'code': '+677', 'name': 'Solomon Islands'},
    {'id': 'KI', 'code': '+686', 'name': 'Kiribati'},
    {'id': 'TV', 'code': '+688', 'name': 'Tuvalu'},
    {'id': 'NR', 'code': '+674', 'name': 'Nauru'},
    {'id': 'PW', 'code': '+680', 'name': 'Palau'},
    {'id': 'FM', 'code': '+691', 'name': 'Micronesia'},
    {'id': 'MH', 'code': '+692', 'name': 'Marshall Islands'},
  ];
}
